### ISSUE TITLE
I can't recive the RX2 packet

### ISSUE THREAD

**Issue by bitconnector** [bitconnector/LittleWan#1]
Hi I would be grateful if someone could help me out with this one

I'm successfully reciving the RX1 frame but I never recive something on RX2

After sending a `confirmed uplink` the console on my gateway shows me, that it would send `gs.down.send` 
```
      "rx1_delay": 1,
      "rx1_data_rate": {
        "lora": {
          "bandwidth": 125000,
          "spreading_factor": 7
        }
      },
      "rx1_frequency": "868100000",
      "rx2_data_rate": {
        "lora": {
          "bandwidth": 125000,
          "spreading_factor": 12
        }
      },
      "rx2_frequency": "869525000",
      "priority": "HIGHEST",
      "frequency_plan_id": "EU_863_870_TTN"
```

I'm still not able to recive anything with a different device listening continously using this settings:
```
  if (!LoRa.begin(869525000))
  {
    Serial.println("LoRa init failed. Check your connections.");
    while (true)
      ; // if failed, do nothing
  }
  LoRa.setPreambleLength(8);
  LoRa.setSyncWord(0x34);
  LoRa.disableCrc();
  LoRa.setCodingRate4(5);
  LoRa.setSpreadingFactor(12);
  LoRa.enableInvertIQ();
  LoRa.setSignalBandwidth(125E3);
```

Setting this to frequency 868100000 and SF 7 is working with the RX1 packet so I know the code is working

In the **General settings** tab on the device I selected the **Frequency plan** `Europe 863-870 MHz (SF9 for RX2 - recommended)`, 
**LoRaWAN version** `MAC V1.0.4` and **Regional Parameters version** `PHY V1.0`

Can someone give me a hint of what I'm missing ;)

Thanks in advance

**Comment by chron0** [comment]
I'd be interested in this as well, to be able to send remote control commands. I'll try to tinker with it, maybe we can pull that out of the other lmic/ttn stack libs - perhaps it's a timing issue - iirc the RX2 will be queued up after we send an uplink...

**Comment by bitconnector** [comment]
I finally found the bug while trying to recive downlinks fc00dcacca9bb70839863735be3a4248f37c4d0b 48097f7a079322b13eded519713f548f9d32daa0

In order to get these messages the radio has to be completely reconfigured. Now it is working

For RX2 I still have to find the right settings and timing
